config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'homepage#index'

  post '/upload_csv' => 'homepage#upload_csv', as: :upload_csv
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: :true
  validate :validate_password

  def validate_password
    length = false 
    length = true if password.present? && password&.length >= 10
    lower_case = false
    upper_case = false
    digit = false
    count = 1
    character = nil
    repeated_character = 0
    password&.split('')&.each do |char|
      lower_case = true if char >='a' && char <= 'z'
      upper_case = true if char >= 'A' && char <='Z'
      digit = true if char >= '0' && char <= '9'
      if character == char 
        count += 1 
      else
        count = 1
        character = char
      end
      if count == 3
        repeated_character += 1
        count = 0
      end
    end
    needed_character = 0
    if password.blank?
      needed_character = 10
    else
      contain_digit = 0
      if !lower_case || !upper_case || !digit
        contain_digit += 1 if !lower_case
        contain_digit += 1 if !upper_case
        contain_digit += 1 if !digit
      end
      needed_character += [repeated_character, contain_digit].max
      needed_character += (10 - (needed_character + password.length)) if (needed_character + password.length) < 10
    end
    errors.add(:change, "#{needed_character} characters of #{name}’s password") if needed_character > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
require 'csv'

class HomepageController < ApplicationController

	def index
		@errors = Array.wrap(session[:errors])
		session.delete(:errors) if session[:errors].present?
		@users = User.all
	end

	def upload_csv
		@errors = []
		if params[:csv_file].present?
			data = CSV.parse(File.read(params[:csv_file]))
			data.each do |arr|
				next if arr == data.first
				user = User.find_by(name: arr[0])
				user = User.new(name: arr[0]) if user.blank?
				user.password = arr[1]
				if user.save
					@errors << "#{user.name} was successfully saved"
				else
					@errors << user.errors.full_messages.last
				end
			end
		end
		session[:errors] = @errors
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/index.html.erb
<br><br>
<% @errors.each_with_index do |err, ind| %>
  <p><%= "Row #{ind+1}: " + err %></p>
<% end %>
<br><br>
<%= form_with url: upload_csv_path, method: :post do |form| %>
  <%= form.label :query, "Select CSV File:" %>
  <%= form.file_field :csv_file, accept: '.csv' %>
  <%= form.submit "Upload CSV" %>
<% end %>

<table>
  <tr>
    <th>Name</th>
    <th>Password</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.password %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>